data = [
    {'name': 'Lionel Messi', 'follower_count': 400000000, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Shakira', 'follower_count': 200000000, 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'LeBron James', 'follower_count': 120000000, 'description': 'Basketball player', 'country': 'USA'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 500000000, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Rihanna', 'follower_count': 180000000, 'description': 'Singer', 'country': 'Barbados'},
    {'name': 'Selena Gomez', 'follower_count': 290000000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Emma Watson', 'follower_count': 70000000, 'description': 'Actress', 'country': 'UK'},
    {'name': 'Beyoncé', 'follower_count': 250000000, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Dwayne Johnson', 'follower_count': 240000000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Taylor Swift', 'follower_count': 380000000, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Kylie Jenner', 'follower_count': 380000000, 'description': 'Entrepreneur/Reality TV', 'country': 'USA'},
    {'name': 'Ariana Grande', 'follower_count': 250000000, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Chris Hemsworth', 'follower_count': 78000000, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Kim Kardashian', 'follower_count': 350000000, 'description': 'Reality TV star/Entrepreneur', 'country': 'USA'},
    {'name': 'Kendall Jenner', 'follower_count': 250000000, 'description': 'Model', 'country': 'USA'},
    {'name': 'Usain Bolt', 'follower_count': 120000000, 'description': 'Sprinter', 'country': 'Jamaica'},
    {'name': 'Jennifer Lopez', 'follower_count': 200000000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Zendaya', 'follower_count': 230000000, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Kanye West', 'follower_count': 160000000, 'description': 'Rapper/Producer', 'country': 'USA'},
    {'name': 'Justin Bieber', 'follower_count': 370000000, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Drake', 'follower_count': 210000000, 'description': 'Rapper', 'country': 'Canada'},
    {'name': 'Oprah Winfrey', 'follower_count': 60000000, 'description': 'TV Host', 'country': 'USA'},
    {'name': 'Zac Efron', 'follower_count': 80000000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Dakota Johnson', 'follower_count': 150000000, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Katy Perry', 'follower_count': 250000000, 'description': 'Singer', 'country': 'USA'},
    {'name': 'Tom Hanks', 'follower_count': 80000000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Miley Cyrus', 'follower_count': 160000000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Natalie Portman', 'follower_count': 25000000, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Will Smith', 'follower_count': 150000000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Angelina Jolie', 'follower_count': 120000000, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Scarlett Johansson', 'follower_count': 150000000, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Brad Pitt', 'follower_count': 95000000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Gigi Hadid', 'follower_count': 75000000, 'description': 'Model', 'country': 'USA'},
    {'name': 'Justin Timberlake', 'follower_count': 60000000, 'description': 'Singer/Actor', 'country': 'USA'},
    {'name': 'David Beckham', 'follower_count': 100000000, 'description': 'Footballer', 'country': 'UK'},
    {'name': 'Priyanka Chopra', 'follower_count': 95000000, 'description': 'Actress', 'country': 'India'},
    {'name': 'Chris Evans', 'follower_count': 90000000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Kourtney Kardashian', 'follower_count': 190000000, 'description': 'Reality TV star', 'country': 'USA'},
    {'name': 'Ryan Reynolds', 'follower_count': 120000000, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Kylie Minogue', 'follower_count': 50000000, 'description': 'Singer', 'country': 'Australia'},
    {'name': 'Snoop Dogg', 'follower_count': 30000000, 'description': 'Rapper', 'country': 'USA'},
    {'name': 'Kim Jong-Un', 'follower_count': 1000000, 'description': 'Political leader', 'country': 'North Korea'},
    {'name': 'Vladimir Putin', 'follower_count': 2000000, 'description': 'Political leader', 'country': 'Russia'},
    {'name': 'Barack Obama', 'follower_count': 130000000, 'description': 'Former US President', 'country': 'USA'},
    {'name': 'Michelle Obama', 'follower_count': 100000000, 'description': 'Former First Lady', 'country': 'USA'},
    {'name': 'Adele', 'follower_count': 280000000, 'description': 'Singer', 'country': 'UK'},
    {'name': 'Kate Middleton', 'follower_count': 50000000, 'description': 'Duchess of Cambridge', 'country': 'UK'},
    {'name': 'Shawn Mendes', 'follower_count': 65000000, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Bill Gates', 'follower_count': 170000000, 'description': 'Entrepreneur/Philanthropist', 'country': 'USA'},
    {'name': 'Melania Trump', 'follower_count': 20000000, 'description': 'Former First Lady', 'country': 'Slovenia'}
]
